/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/idle.glb -o src/components/Idle.jsx -k -K -r public 
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Idle({ happy, wave, happy2, ...props }) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/idle.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions, names } = useAnimations(animations, group);
  materials["Material.022"].color.set("yellow");
  console.log(actions);
  useEffect(() => {
    if (happy) {
      actions[names[5]].fadeIn(0.5).play().reset();
    } else if (wave) {
      actions[names[2]].fadeIn(0.5).play().reset();
    } else if (happy2) {
      actions[names[6]].fadeIn(0.5).play().reset();
    } else actions[names[1]].fadeIn(0.5).play().reset();
  }, [happy, wave, happy2]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="body001"
            geometry={nodes.body001.geometry}
            material={materials["Material.022"]}
            skeleton={nodes.body001.skeleton}
          />
          <skinnedMesh
            name="feet001"
            geometry={nodes.feet001.geometry}
            material={materials["Material.021"]}
            skeleton={nodes.feet001.skeleton}
          />
          <skinnedMesh
            name="hands"
            geometry={nodes.hands.geometry}
            material={materials["Material.024"]}
            skeleton={nodes.hands.skeleton}
          />
          <skinnedMesh
            name="head001"
            geometry={nodes.head001.geometry}
            material={materials["Material.023"]}
            skeleton={nodes.head001.skeleton}
          />
          <skinnedMesh
            name="path14001"
            geometry={nodes.path14001.geometry}
            material={materials["SVGMat.026"]}
            skeleton={nodes.path14001.skeleton}
          />
          <skinnedMesh
            name="path15001"
            geometry={nodes.path15001.geometry}
            material={materials["SVGMat.027"]}
            skeleton={nodes.path15001.skeleton}
          />
          <skinnedMesh
            name="path16001"
            geometry={nodes.path16001.geometry}
            material={materials["SVGMat.028"]}
            skeleton={nodes.path16001.skeleton}
          />
          <skinnedMesh
            name="path17001"
            geometry={nodes.path17001.geometry}
            material={materials["SVGMat.029"]}
            skeleton={nodes.path17001.skeleton}
          />
          <skinnedMesh
            name="path5"
            geometry={nodes.path5.geometry}
            material={materials["SVGMat.025"]}
            skeleton={nodes.path5.skeleton}
          />
          <skinnedMesh
            name="path6"
            geometry={nodes.path6.geometry}
            material={materials["SVGMat.025"]}
            skeleton={nodes.path6.skeleton}
          />
          <skinnedMesh
            name="path9"
            geometry={nodes.path9.geometry}
            material={materials["SVGMat.025"]}
            skeleton={nodes.path9.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/idle.glb");
