/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/zatplanet4.glb -o src/components/Planet3.jsx -k -K -r public 
*/

import React from "react";
import { Html, useGLTF } from "@react-three/drei";
import { useAtom } from "jotai";
import { currentPageAtom } from "./ui";
import { degToRad } from "three/src/math/MathUtils.js";

export const OverlayItem = ({
  className = "",
  title,
  desc,
  bgColor,
  ...props
}) => {
  const [currentPage] = useAtom(currentPageAtom);

  return (
    <Html
      transform
      distanceFactor={1.2}
      center
      className={`w-64 rounded-xl overflow-hidden ${
        currentPage === "store" ? "" : "opacity-0"
      } transition-opacity duration-1000 ${className} `}
      {...props}
    >
      <div className="bg-white bg-opacity-90 backdrop-blur-lg text-xl p-2 w-full flex flex-col gap-4">
        <h2 className="font-bold">{title}</h2>
        <p>{desc}</p>
        <button
          className={`${bgColor} hover:bg-opacity-50 transition-colors duration-500 px-4 py-2 font-bold text-white rounded-full`}
        >
          Další info
        </button>
      </div>
    </Html>
  );
};

export function Planet3({ html, ...props }) {
  const { nodes, materials } = useGLTF("/models/zatplanet4.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Scene_Collection" />
        <group name="Sphere001" />
        <mesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials.Poliigon_GrassPatchyGround_4585_4K}
          scale={[4.002, 4.018, 4.003]}
        />
        <group>
          <mesh
            name="Sphere003"
            geometry={nodes.Sphere003.geometry}
            material={materials.Poliigon_GrassPatchyGround_4585_4K}
            scale={[4.002, 4.018, 4.003]}
          />
          {html && (
            <group
              position-x={0.1}
              position-y={2}
              position-z={0}
              rotation-x={-degToRad(30)}
            >
              <OverlayItem
                title={"Hodnoty"}
                desc={"nějaký pěkný a výstižný text"}
                bgColor={"bg-yellow-500"}
                className="transition delay-1000"
              />
            </group>
          )}
        </group>
        <group name="Overlay">
          <mesh
            name="Sphere004"
            geometry={nodes.Sphere004.geometry}
            material={materials.Poliigon_GrassPatchyGround_4585_4K}
            scale={[4.002, 4.018, 4.003]}
          />
          {html && (
            <group
              position-x={0.1}
              position-y={-3}
              position-z={0}
              rotation-x={-degToRad(30)}
            >
              <OverlayItem
                title={"Vize"}
                desc={"nějaký pěkný a výstižný text"}
                bgColor={"bg-purple-500"}
                className="transition delay-1000"
              />
            </group>
          )}
        </group>
        <mesh
          name="Sphere005"
          geometry={nodes.Sphere005.geometry}
          material={materials.Poliigon_GrassPatchyGround_4585_4K}
          scale={[4.002, 4.018, 4.003]}
        />

        <mesh
          name="Sphere002"
          geometry={nodes.Sphere002.geometry}
          material={materials.Poliigon_GrassPatchyGround_4585_4K}
          scale={[4.002, 4.018, 4.003]}
          position={[-6.985, 4.56, -4.674]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/zatplanet4.glb");
